Vagrant.configure(2) do |config|
  
  config.vm.box = "rudolfochrist/ubuntu-desktop"

  
   config.vm.provider "virtualbox" do |vb|
     
     vb.gui = true
  
     
     vb.memory = "1024"
   end
  
   config.vm.provision "shell", inline: <<-SHELL
	 sudo apt-get update	 
     sudo apt-get -qy install openjdk-7-jdk
	 sudo apt-get -qy install ant
	 sudo apt-get -qy install git
	 sudo apt-get install flashplugin-installer 
	sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-calc.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-writer.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-impress.desktop"
	sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"
	sudo rm -f "/usr/share/applications/unity-control-center.desktop"	
	 cd Desktop
	 mkdir tool
	 cd tool
	 git clone https://github.com/SoftwareEngineeringToolDemos/FSE-2014-XMLMate
	 cd ..
	 cp tool/FSE-2014-XMLMate/scriptTool.tar.gz .	 
	 tar -xvf scriptTool.tar.gz
	 cd XMLMate
	 ./usage-example-freedots.sh
	 ./buildScipt.sh	 
	 cd ..
	 rm -rf tool	 
   SHELL
end
